AspDemoMiddleware/Models/TaskItem.cs
namespace AspDemoMiddleware.Models
{
    public class TaskItem
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime End { get; set; }
        public bool IsCompleted { get; set; } = false;
    }
}

AspDemoMiddleware/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AspDemoMiddleware.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AspDemoMiddleware/Pages/Index.cshtml.cs
using AspDemoMiddleware.Models;
using AspDemoMiddleware.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspDemoMiddleware.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ITaskItemService _tis;
        public List<TaskItem> TaskItems { get; set; } = new List<TaskItem>();

        public IndexModel(ITaskItemService service)
        {
            _tis = service;
        }

        public void OnGet()
        {
            TaskItems = _tis.GetTaskItems();
        }

        public IActionResult OnGetAddTask()
        {
            TaskItems = _tis.GetTaskItems();
            int count = TaskItems.Count;
            var taskItem = new TaskItem()
            {
                Id = count + 1,
                Name = $"úkol {count + 1}",
                End = DateTime.Now.AddDays(count + 1),
                IsCompleted = Random.Shared.Next(0, 2) == 0
            };

            _tis.CreateTaskItem(taskItem);

            return RedirectToPage("/Index");
        }

        public IActionResult OnGetDeleteTask(int taskId)
        {
            _tis.DeleteTaskItem(taskId);
            return RedirectToPage("/Index");
        }

        public IActionResult OnGetRemoveAll()
        {
            _tis.DeleteAllTaskItems();
            return RedirectToPage("/Index");
        }

        public IActionResult OnGetFinished(int id)
        {
            _tis.FinishTaskItem(id);
            return RedirectToPage("/Index");
        }
    }
}

AspDemoMiddleware/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspDemoMiddleware.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AspDemoMiddleware/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Úkoly</h1>
    @if(Model.TaskItems.Count == 0)
    {
        <p>Zatím zde nejsou žádné úkoly.</p>
    }
    else
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Název</th>
                    <th>Datum</th>
                    <th>Stav</th>
                    <th>Akce</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in @Model.TaskItems)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.End</td>
                        <td>
                            <a class=@(item.IsCompleted ? "btn btn-warning" : "btn btn-primary") 
                                asp-page-handler="Finished" 
                                asp-route-id="@item.Id">@(item.IsCompleted ? "Obnovit" : "Dokončit")</a>
                        </td>
                        <td>
                            <a class="btn btn-danger" asp-page-handler="DeleteTask" asp-route-taskId="@item.Id">Smazat</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h2 class="display-6">Počet úkolů: @Model.TaskItems.Count</h2>
        <h2 class="display-6">Dokončené úkoly: @Model.TaskItems.Where(x => x.IsCompleted).Count()</h2>
    }
</div>

<div>
    <a class="btn btn-secondary" asp-page-handler="AddTask">Přidat úkol</a>
    @if(Model.TaskItems.Count > 0)
    {
        <a class="btn btn-danger" asp-page-handler="RemoveAll">Smazat vše</a>
    }
</div>

AspDemoMiddleware/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspDemoMiddleware</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspDemoMiddleware.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AspDemoMiddleware</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspDemoMiddleware - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>